extend type Asset {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Asset", purpose: IMPLICIT_KEY_FIELD)
}
extend type Incident {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Incident", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Incident`.`asset`. It must match the value of `Asset`.`id`. See `@ref` for how to customize it.
  """
  assetId: UUID! @fdc_generated(from: "Incident.asset", purpose: IMPLICIT_REF_FIELD)
}
extend type Service {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Service", purpose: IMPLICIT_KEY_FIELD)
}
extend type Ticket {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Ticket", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Ticket`.`asset`. It must match the value of `Asset`.`id`. See `@ref` for how to customize it.
  """
  assetId: UUID @fdc_generated(from: "Ticket.asset", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Ticket`.`assignedTo`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  assignedToId: UUID @fdc_generated(from: "Ticket.assignedTo", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
